### PR TITLE
changed paths for images and links, hopefully got them all

### PR DESCRIPTION
**Pull request by dinger1986**

### CODE REVIEW

**Comment by rustdesk** [comment]
Not working

**Comment by rustdesk** [comment]
and broke many things.

**Comment by rustdesk** [comment]
image

**Comment by rustdesk** [comment]
Let me handle this. I think you are not good at this.

**Comment by dinger1986** [comment]
That's offensive!

Obviously a small mistake did you see ALL the changes?

**Comment by dinger1986** [comment]
image

`<style>body {text-align: right}</style>` was in the file and does nothing with `hugo serve`.

Yeah of course the relative path doesnt work for the others, again doesnt show on hugo

**Comment by rustdesk** [comment]
No worries, I have modified and deployed.

**Pull request merged**
