### PR TITLE
Add article "NAT Loopback issues"

### PR DESCRIPTION
**Pull request by xlionjuan**
Servral things need to check/confirm

1. Is this path appropriate? It is currently under ``self-host/rustdesk-server-oss/``, should this put at ``self-host/``?
2. Is this article has big problems of its outline?
3. Correct the grammar or change the explaination to make others more easy to understand.

If 1, 2 is okay, please merge, 3 could be fix latter.

### CODE REVIEW

**Comment by rustdesk** [comment]
How about put as 2.5?

image

**Comment by rustdesk** [comment]
But it not easy to be found by user.

**Comment by xlionjuan** [comment]
how about put as 2.5 and add a notice like this in OSS and Pro?

截圖 2024-02-26 下午2 44 16

**Comment by rustdesk** [comment]
Agree

**Pull request merged**
