### PR TITLE
Add documentation on using env variables

### PR DESCRIPTION
**Pull request by botanicvelious**
Add documentation page for hard-coding values via environment variables.

### CODE REVIEW

**Comment by rustdesk** [comment]
Need add something to tell them how to use github CI for building. Github CI is much easier for most of guys rather than building on their machine.

**Comment by rustdesk** [comment]
e.g., how to fork, how to set github secrets, how to run the CI manually, etc.

**Comment by rustdesk** [comment]
BTW, i changed `RS_PUB_KEY_VAL` to `RS_PUB_KEY`.

**Comment by botanicvelious** [comment]
Updated RS_PUB_KEY, also saw you changed how RS_PUB_KEY_VAL worked, i assume thats a better way to do it 👍 

Added a page for building all with github actions

**Pull request merged**
