### PR TITLE
Small corrections

### PR DESCRIPTION
**Pull request by Mr-Update**

### CODE REVIEW

**Comment by xlionjuan** [comment]
Why changed from relative path to absolute path?

**Comment by rustdesk** [comment]
Thank you very much. But chaging from `/docs/...` to `https://rustdesk.com/docs/...` seems not good.

**Comment by Mr-Update** [comment]
@rustdesk, @xlionjuan 
With `/docs/...` you see the links in dark gray, difficult to distinguish from the black text:

Image1

With `https://rustdesk.com/docs/...` you can see the links in the usual blue color:

Image2

In addition, the other links already use the absolute path.

**Comment by xlionjuan** [comment]
I think the theme can be adjusted.

For you said, some links are already using absolute path, I think everyone should discuss this, this situation will pain when RustDesk migrate the web server to another subdomain or path.

**Comment by Mr-Update** [comment]
Not only some, but all other links use the absolute path.

If the subdomain or path is changed, the adjustment can simply be carried out across all files using *search and replace*.

**Pull request merged**
